name: Publish Package

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:

  validate:
    name: Validate
    continue-on-error: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test
